version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Code checked out"

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save
      - run:
          name: Run build
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:  
          docker_layer_caching: true
      - run:
          name: Set execute permission
          command: chmod +x deploy_script.sh
      - run:
          name: Deploy application
          command: ./deploy_script.sh

  start_ngrok:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y wget unzip
      - run:
          name: Install Ngrok
          command: |
            wget https://bin.equinox.io/c/111111/ngrok-stable-linux-amd64.zip -O ngrok.zip
            unzip ngrok.zip
            sudo mv ngrok /usr/local/bin
            rm ngrok.zip
      - run:
          name: Start Ngrok
          command: ngrok http 3000  

workflows:
  version: 2
  deploy_flow:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
      - start_ngrok:  # เริ่ม Ngrok หลังจาก deploy
          requires:
            - deploy
