version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Code checked out"

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --save
      - run:
          name: Run build
          command: npm run build

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:  
          docker_layer_caching: true
      - run:
          name: Set execute permission
          command: chmod +x deploy_script.sh
      - run:
          name: Deploy application
          command: ./deploy_script.sh

  start_ngrok:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Update sources.list for Debian Stretch
          command: |
            echo "deb http://archive.debian.org/debian/ stretch main" | sudo tee /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian-security/ stretch/updates main" | sudo tee -a /etc/apt/sources.list
            echo "Acquire::Check-Valid-Until false;" | sudo tee /etc/apt/apt.conf.d/10disable-check-valid-until
      - run:
          name: Update package lists
          command: sudo apt-get update
      - run:
          name: Install Ngrok
          command: sudo apt-get install -y ngrok
      - run:
          name: Start Ngrok
          command: ngrok http 3000  # แทนที่ 3000 ด้วยพอร์ตที่แอปพลิเคชันรันอยู่

workflows:
  version: 2
  deploy_flow:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
      - start_ngrok:  # เริ่ม Ngrok หลังจาก deploy
          requires:
            - deploy
