version: 2.1

jobs:
  checkout_code:
    docker:
      - image: circleci/node:14  # เลือกภาพ Docker ตามที่ใช้
    steps:
      - checkout  # ดึงโค้ดจาก Git
      - run: echo "Code checked out"

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install  # ติดตั้ง dependency
      - run:
          name: Run build
          command: npm run build  # สั่ง build

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Deploy application
          command: ./deploy_script.sh  # ใช้สคริปต์ deploy ที่คุณเตรียมไว้

workflows:
  version: 2
  deploy_flow:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
